#!/usr/bin/env bash
# A script that receives a domain name as an argument
# and returns information about all of its subdomains

declare -a subdomains=("www" "lb-01" "web-01" "web-02")

if [ "$2" ] ; then
    info=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | sed -n '2p')
    record=$(echo "$info" | awk '{ print $4 }')
    ip=$(echo "$info" | awk '{ print $5 }')
    echo "The subdomain $2 is a $record record and points to $ip"

else
    for sub in "${subdomains[@]}"; do
        info=$(dig "$sub.$1" | grep -A1 'ANSWER SECTION:' | sed -n '2p')
        record=$(echo "$info" | awk '{ print $4 }')
        ip=$(echo "$info" | awk '{ print $5 }')
	echo "The subdomain $sub is a $record record and points to $ip"
    done
fi
