#!/usr/bin/bash
# Start nginx and configure it to listen to port 80
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
