#!/usr/bin/env bash
# This script is displaying 12 hours and 59 minutes of a clock
h=0
LAST=12
m=1
END=60
while [ "$h" -le $LAST ]; do
	echo "Hour: $h"
	while [ "$m" -lt $END ]; do
		echo "$m"
		m=$((m+1))
	done
	m=1
	h=$((h+1))
done
