#!/usr/bin/env bash
# A script that finds information about 'holbertonschool' file
FILE="holbertonschool"
if [ ! $FILE ]
then
	echo "$FILE file does not exist"
else
	echo "$FILE file exists"
	if [ ! -s $FILE ]
	then
		echo "$FILE file is empty"
	else
		echo "$FILE file is not empty"
	fi
	if [ -f $FILE ]
	then
		echo "$FILE file is a regular file"
	fi
fi
