#!/usr/bin/env bash
# Installs nginx on server then sets up a redirect and a 404 error message
redir="\tlocation = /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=kH6QJzmLYtw;\n\t}"
file="/etc/nginx/sites-enabled/default"
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo sed -i "37i\ $redir" $file
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i "s/#error_page/error_page/g" $file
sudo service nginx restart
