#!/usr/bin/env bash
# Run nginx as nginx user and listen on all active ports
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo sed -i "s/80/8080/" /etc/nginx/sites-available/default
sudo -u nginx nginx
